### PR TITLE
Able to build for ARM

### PR DESCRIPTION
**Pull request by a0s**

### CODE REVIEW

**Comment by jangaraj** [comment]
How does it work? Because `FROM debian:jessie` => base image is still amd64. Am I missing something?

**Comment by a0s** [comment]
Hm, i dont have any problem with debian:jessie itself
```bash
root@manager:~# docker run --rm -it debian:jessie bash
root@600e89dcc38c:/# uname -a
Linux 600e89dcc38c 4.14.29-125 #1 SMP PREEMPT Thu Mar 22 21:40:52 UTC 2018 armv7l GNU/Linux
root@600e89dcc38c:/# exit
root@manager:~# uname -a
Linux manager 4.14.29-125 #1 SMP PREEMPT Thu Mar 22 21:40:52 UTC 2018 armv7l armv7l armv7l GNU/Linux
```

**Comment by jangaraj** [comment]
Actually, `debian:jessie` is multiarch image:
```
$ curl -sL https://registry.hub.docker.com/v2/repositories/library/debian/tags/jessie  | jq .
{
  "name": "jessie",
  "full_size": 52608519,
  "images": [
    {
      "size": 52795472,
      "architecture": "s390x",
      "variant": null,
      "features": null,
      "os": "linux",
      "os_version": null,
      "os_features": null
    },
    {
      "size": 51817165,
      "architecture": "ppc64le",
      "variant": null,
      "features": null,
      "os": "linux",
      "os_version": null,
      "os_features": null
    },
    {
      "size": 52787625,
      "architecture": "386",
      "variant": null,
      "features": null,
      "os": "linux",
      "os_version": null,
      "os_features": null
    },
    {
      "size": 49933463,
      "architecture": "arm64",
      "variant": null,
      "features": null,
      "os": "linux",
      "os_version": null,
      "os_features": null
    },
    {
      "size": 48702073,
      "architecture": "arm",
      "variant": null,
      "features": null,
      "os": "linux",
      "os_version": null,
      "os_features": null
    },
    {
      "size": 50890011,
      "architecture": "arm",
      "variant": null,
      "features": null,
      "os": "linux",
      "os_version": null,
      "os_features": null
    },
    {
      "size": 52608519,
      "architecture": "amd64",
      "variant": null,
      "features": null,
      "os": "linux",
      "os_version": null,
      "os_features": null
    }
  ],
...
```
That's a trick 👍

**Comment by jangaraj** [comment]
Thx.

**Pull request merged**
